# Execute serverless in the container created with the Dockerfile present in same folder
name: coach
description: 'Setup in ./coach folder'

run: git status
run: git check master
run: git status
run: ls -l
uses: ./coach

name: Check npm modules vulnerabilities
run: npm audit

      # Install nodejs packages listed in package*.json.
      # Node 10 is current default in ubuntu-latest
run: npm install --only=prod

      # run "serverless deploy --verbose" in a docker container 
name: Deploy lambda
uses: serverless/github-action@v1.49.0  # v1.52/1.53 have a bug
env: # all mandatory
  # AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-west-2
  AWS_STAGE: dev
  # GITHUB APP
  APP_ID: 43025
  WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
with:
  args: deploy --verbose
